# Generated by Django 4.2.21 on 2025-08-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_anchored',
            field=models.BooleanField(default=False),
        ),
    ]
